version: '3.8'

services:
  web:
    build: .
    container_name: aiflux-docs-app
    restart: always
    ports:
      - "5005:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      # No mapeamos el código completo en prod para mayor seguridad, 
      # pero sí static si necesitas persistencia de archivos subidos localmente.